model:
  name: mnist_regressor

train:
  # Epoch
  start_epoch: 0
  end_epoch: 20
  check_val_every_n_epoch: 1  # run validation every n epoch

  # Optimizer & Scheduler mode
  optimizer:
    mode: 'adam'
  scheduler:
    mode: ReduceLROnPlateau

# Validation & Visualization
valid:
  visualize_result: false
  visualize_sample: 1

test:
  visualize_result: false
  
data:
  name: 'mnist'
  root: '../../dataset/mnist/'
  batch_size: 10
  num_workers: 8

criterion:
  key_pairs:
    # list of loss terms for this model
    - 'cross_entropy'

saver:  # save model ckpt, training state
  monitor_keys:
    # key/criteria to determine best (l for low,h for high)
    - 'val-total_loss/l'   # low total loss is good
  save_every_n_epoch: 10   # checkpoint auto save interval
  backup_every_n_epoch: 100 # backup interval