model:
  name: model_name

train:
  # Epoch
  start_epoch: 0
  end_epoch: 10000
  check_val_every_n_epoch: 1

  # Batch size & worker
  batch_size: 10
  num_workers: 8

  # Optimizer & Scheduler
  optimizer:
    mode: 'adam'
  scheduler:
    mode: ReduceLROnPlateau

# Validation & Visualization
valid:
  interval_epoch: 10
  interval_step: ~
  visualize_result: true
  visualize_sample: 1

test:
  batch_size: 1
  num_workers: 8
  visualize_result: true
  
data:
  root: 'DATA_PATH_FOR_THIS_MODEL'

criterion:
  key_pairs:
    # list of loss terms for this model
    - 'l1_loss'

saver:  # save model ckpt, training state
  monitor_keys:
    # key/criteria to determine best (l for low,h for high)
    - 'val-total_loss/l'   # low total loss is good
  save_every_n_epoch: 10   # checkpoint auto save interval
  backup_every_n_epoch: 100 # backup interval